### PR TITLE
rAF polyfill for IE9 and iOS6

### PR DESCRIPTION
**Pull request by aMarCruz**
@johan-gorter here is the polyfill (add <600 bytes minimized).
Included and tested with maquette examples in IE9-11 (w/o it, none of the examples works in IE9).
I can't finish css-transitions example, throws error in
https://github.com/AFASSoftware/maquette/blob/master/src/css-transitions.js#L15

maybe you wanna see https://github.com/EvandroLG/transitionEnd/blob/master/src/transition-end.js

### CODE REVIEW

**Comment by aMarCruz** [comment]
sorry this is wrong pr

**Comment by johan-gorter** [comment]
If I interpret your finding correctly, CSS transitions are not doable in IE9?

**Comment by aMarCruz** [comment]
right. It is not supported in IE9.

Browser support and known issues: http://caniuse.com/#feat=css-transitions

**Comment by aMarCruz** [comment]
I test this behavior in a VirtualBox machine with Win7+IE9.
You can check it with IE11 : Hit F12, then, in the toolbar near to the right, change "Edge" to "9" and proceed with the examples.

**Pull request merged**
