### PR TITLE
Allow eventHandlerInterceptor override in createProjector

### PR DESCRIPTION
**Pull request by soyuka**
Let me know if I need to commit dist files too.

### CODE REVIEW

**Comment by johan-gorter** [comment]
Hello,

We will take care of the dist files when shipping a new version.

I wonder about the use-case you are trying to fulfil. We had similar discussions on #31 and #51. The only reason people wanted to replace the eventHandlerInterceptor was to prevent unneeded render/diff cycles. We still want to create a more versatile drop-in replacement for the Projector to make this possible. If your use-case is different, please let us know.

**Comment by soyuka** [comment]
Actually I thought it was catching every events so that I could call a
function on my own on each render cycle. Maybe you could mention it's real
purpose in the docs. Also, as it was written in the docs that the
`eventhandlerinterceptor` could be overridden I didn't understood why it is
not overridable in `createProjector`.

After tweaking this I understood that it wasn't for this purpose so feel
free to close this ;).
As a workaround I'm calling my own function in every event call (see
options.onUpdate in
https://github.com/soyuka/dpicker/blob/master/src/dpicker.js).

Le ven. 24 juin 2016 à 12:56, Johan Gorter <notifications@github.com> a
écrit :

**Comment by soyuka** [comment]
Actually I thought it was catching every events so that I could call a
function on my own on each render cycle. Maybe you could mention it's real
purpose in the docs. Also, as it was written in the docs that the
`eventHandlerInterceptor` could be overridden I didn't understood why it is
not overridable in `createProjector`.

After tweaking this I understood that it wasn't for this purpose so feel
free to close this ;).
As a workaround I'm calling my own function in every event call (see [here](https://github.com/soyuka/dpicker/blob/master/src/dpicker.js#L83) for example).

**Comment by johan-gorter** [comment]
I think that modifying the projector to intercept every event would be too dramatic for this use-case. If you were to add hover logic (with onmouseenter onmouseleave etc) for example or other events that do not change the value immediately, onChange would fire needlessly.

Good luck with your date picker project!

**Pull request closed without merging**
