### PR TITLE
Simplify selector parsing

### PR DESCRIPTION
**Pull request by paldepind**
This PR simplifies the selector parsing algorithm – shortening it by 18 lines.

### CODE REVIEW

**Comment by aMarCruz** [comment]
Is maquette IE8 compatible? classLib does not exists in IE8.
Anyway, I don't like (and have no support to) IE8

**Comment by paldepind** [comment]
@aMarCruz `classList` can be polyfilled. Maquette has [a polyfill right here](https://github.com/AFASSoftware/maquette/blob/master/src/maquette-polyfills.js).

But this pull request does not influence browser support in any way. The only usage of `classList` is the one that was already there.

**Comment by johan-gorter** [comment]
Maquette currently supports IE back down to IE9 (through the mentioned polyfill). There is no browser-specific code in the maquette library itself and we would like to keep it that way if possible.

**Comment by johan-gorter** [comment]
@paldepind could you please sign the CLA we just added? It is located at: https://www.clahub.com/agreements/AFASSoftware/maquette

**Comment by paldepind** [comment]
I've signed it.

**Comment by johan-gorter** [comment]
Cool, your shorter code runs fine. I also added some extra unit tests for it (and I needed to polyfill classList for jsdom).

**Comment by aMarCruz** [comment]
@johan-gorter ye thanks, I like your polyfill.
But, there are bugs with IE 10/11 and Firefox <26, where classList.add and classList.remove exist but support only one argument at a time.
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

In IE 10 and Firefox <24, classList.toggle does not support the second argument.
http://caniuse.com/#feat=classlist

There are issues with **requestAnimationFrame** in iOS6, too.
https://bugs.webkit.org/show_bug.cgi?id=132794, http://shitwebkitdoes.tumblr.com/post/47186945856/native-requestanimationframe-broken-on-ios-6
...
I have a polyfill in https://gist.github.com/aMarCruz/061f9cced1e5c0855bb7, I thinks it is short and efficient code. May I create a PR?

**Comment by johan-gorter** [comment]
@aMarCruz Maquette is not using the more exotic parts of classList, just the simple add and remove functions. They seem to be unaffected by the bugs you mentioned. 

The requestAnimationFrame on IOS6 does seem like an issue. You are welcome to add the polyfill to the existing maquette-polyfils.js file in a pull request then I will merge it in.

Maybe you can use the tests in /browser-tests/ to verify that there are no other issues in IOS6?

**Comment by aMarCruz** [comment]
:ok_hand: I will and will test a patch of maquette in ie9, today. I don't have ios6.

**Pull request merged**
